### ISSUE TITLE
Can't play multiplayer?

### ISSUE THREAD

**Issue by tuandatdavid** [antunnitraj/Prism-Launcher-PolyMC-Offline-Bypass#4]
Well, I can't play multiplayer. Is this blocked cuz this is cracked? Can I bypass it? 

(sorry for these stupid questions)

**Comment by antunnitraj** [comment]
You can only play singleplayer and multiplayer servers where **online mode** is **disabled**. That means you can only play on so called **"cracked" servers**. If you want to play with your friends then you can spin up an aternos server, go to server options and turn on the "Cracked" option. That will disable online mode and make you able to join that server along with your other friends.

**Comment by tuandatdavid** [comment]
> You can only play singleplayer and multiplayer servers where **online mode** is **disabled**. That means you can only play on so called **"cracked" servers**. If you want to play with your friends then you can spin up an aternos server, go to server options and turn on the "Cracked" option. That will disable online mode and make you able to join that server along with your other friends.

Thank you, I use sklauncher on my windows pc, but I had to use prism on my mac cuz I installed asahi fedora. I meant like multi-player is greyed out, so I can't even join the cracked server of my friend

**Comment by tuandatdavid** [comment]
oh well nevermind, it just doesn't work on 1.16
