### ISSUE TITLE
Unable to apply the bypass on (9.0-develop)

### ISSUE THREAD

**Issue by gemifo** [antunnitraj/Prism-Launcher-PolyMC-Offline-Bypass#7]
so, I've got a version of Prism Launcher on `9.0-develop`, installed it from the chaotic-aur, package named `prismlauncher-git`.

after it got installed, I launched it, closed it, put the `accounts.json` into the right location, then launch it and create an offline account, right?

except, it gave me a message that said:
```
You must add a Microsoft account that owns Minecraft before you can add an offline account.

If you have lost your account you can contact Microsoft for support.
```
and it does have the, `No profile (<Offline>)` entry. I'm really confused... did I do something wrong?
so, this is on Arch Linux.
![onarch](https://github.com/user-attachments/assets/483a36a2-41b3-4943-9d0b-ad3b9085e78e)

I did also try it on Ubuntu 22.04, and the same thing.
![Screenshot from 2024-08-09 17-13-13](https://github.com/user-attachments/assets/7f1a9cb8-c876-4d3f-8004-77762d540409)

**Comment by antunnitraj** [comment]
Hello, thank you for this report!

Just tried it and I got the same result. I'll try to see if there is a way to bypass it still.

**Comment by antunnitraj** [comment]
I managed to bypass the nightly version or Prism Launcher. I will update the repo when it gets released in case they add few more checks.

Until then, you can try to put this in your accounts.json

`{"accounts": [{"entitlement": {"canPlayMinecraft": true,"ownsMinecraft": true},"type": "MSA"}],"formatVersion": 3}`

Make an offline account and set it to default (do not delete the microsoft "No profile" account)

And try to play it

**Comment by antunnitraj** [comment]
I also have to do some cleanup on the readme since PolyMC doesn't need an MSA account anymore

**Comment by gemifo** [comment]
Hi there, yep it worked for me!

if anyone was to have this issue, could this issue be pinned in case? just a suggestion.

and, thank you so much! <3

**Comment by antunnitraj** [comment]
Here :)

**Comment by antunnitraj** [comment]
i updated the repo with the new updated way that works on all versions of the launcher

**Comment by tiziodcaio** [comment]
Ehi, 9.0 here does not work anymore...

**Comment by antunnitraj** [comment]
> Ehi, 9.0 here does not work anymore...

Did you delete the "No profile" account? If you did try again without deleting it.

**Comment by F1L1AN** [comment]
> > Ehi, 9.0 here does not work anymore...
> 
> try again without deleting it.

it doesn't really work on version 9.0

**Comment by morespacemore** [comment]
> > > Ehi, 9.0 here does not work anymore...
> > 
> > 
> > try again without deleting it.
> 
> it doesn't really work on version 9.0

![изображение](https://github.com/user-attachments/assets/1f9383c8-11a0-40ea-bd95-88dbc5dce454)

in version 9.1 everything works and there are no errors if you do not delete the first line
