### ISSUE TITLE
Failed to log in: Invalid session

### ISSUE THREAD

**Issue by ReStranger** [antunnitraj/Prism-Launcher-PolyMC-Offline-Bypass#8]
![image](https://github.com/user-attachments/assets/873f75cf-bc7e-445c-a84f-f8b3f8ea5295)
Version: 9.1 flathub 2024-11-19

I have this error, when i connecting to local server(lan)
```json
{
    "accounts": [
        {
            "entitlement": {
                "canPlayMinecraft": true,
                "ownsMinecraft": true
            },
            "msa-client-id": "",
            "type": "MSA"
        },
        {
            "entitlement": {
                "canPlayMinecraft": true,
                "ownsMinecraft": true
            },
            "profile": {
                "capes": [
                ],
                "id": "f736455463e23b94baeaffe611d28cde",
                "name": "ReStranger",
                "skin": {
                    "id": "",
                    "url": "",
                    "variant": ""
                }
            },
            "type": "Offline",
            "ygg": {
                "extra": {
                    "clientToken": "7938b0a0d83e4c55a8e032325015f5a4",
                    "userName": "ReStranger"
                },
                "iat": 1733090157,
                "token": "0"
            }
        },
        {
            "active": true,
            "profile": {
                "capes": [
                ],
                "id": "530fa97a357f3c1994d30c5c65c18fe8",
                "name": "test",
                "skin": {
                    "id": "",
                    "url": "",
                    "variant": ""
                }
            },
            "type": "Offline",
            "ygg": {
                "extra": {
                    "clientToken": "71a177c64e644f32b507ecb7ee3bdf11",
                    "userName": "test"
                },
                "iat": 1733185300,
                "token": "0"
            }
        }
    ],
    "formatVersion": 3
}
```

**Comment by antunnitraj** [comment]
Are you using the "Open to LAN" function? If not make sure in the server config is specified that online mode is off. With "Open to LAN" it works normally for me.

**Comment by ReStranger** [comment]
I use "Open to LAN"

**Comment by antunnitraj** [comment]
What version of minecraft are you using?

**Comment by ReStranger** [comment]
1.18.2 fabric(no mods)

**Comment by ReStranger** [comment]
Now I checked 1.8.9, same problem

**Comment by ReStranger** [comment]
Btw, json from official account(all tocken and id changed to 1111 or sssss)
```json
{
    "accounts": [
        {
            "active": true,
            "entitlement": {
                "canPlayMinecraft": true,
                "ownsMinecraft": true
            },
            "msa": {
                "exp": 1111111111,
                "extra": {
                    "ext_expires_in": 3600,
                    "state": "ssssssss"
                },
                "iat": 1111111111,
                "refresh_token": "",
                "token": ""
            },
            "msa-client-id": "ssssssssssssssssssssssssssssssssssss",
            "profile": {
                "cape": "ssssssssssssssssssssssssssssssssssss",
                "capes": [
                    {
                        "alias": "Vanilla",
                        "id": "ssssssssssssssssssssssssssssssssssss",
                        "url": "ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss"
                    }
                ],
                "id": "ssssssssssssssssssssssssssssssss",
                "name": "nick",
                "skin": {
                    "data": "",
                    "id": "ssssssssssssssssssssssssssssssssssss",
                    "url": "sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss",
                    "variant": "CLASSIC"
                }
            },
            "type": "MSA",
            "utoken": {
                "exp": 1111111111,
                "extra": {
                    "uhs": "1111111111111111111"
                },
                "iat": 1111111111,
                "token": ""
            },
            "xrp-main": {
                "exp": 1111111111,
                "extra": {
                    "agg": "sssss",
                    "gtg": "sssssssssssss",
                    "prv": "sss",
                    "uhs": "1111111111111111111",
                    "usr": "1111111",
                    "utr": "111",
                    "xid": "1111111111111111"
                },
                "iat": 1111111111,
                "token": ""
            },
            "xrp-mc": {
                "exp": 1111111111,
                "extra": {
                    "uhs": "1111111111111111111"
                },
                "iat": 1111111111,
                "token": ""
            },
            "ygg": {
                "exp": 1111111111,
                "iat": 1111111111,
                "token": ""
            }
        }
    ],
    "formatVersion": 3
}
```

**Comment by antunnitraj** [comment]
I tried with all combinations and I am unable to replicate this issue. Try reinstalling PrismLauncher from scratch. I will close this issue for now.

**Comment by Edgaras91** [comment]
> Btw, json from official account(all tocken and id changed to 1111 or sssss)
> 
> {
>     "accounts": [
>         {
>             "active": true,
>             "entitlement": {
>                 "canPlayMinecraft": true,
>                 "ownsMinecraft": true
>             },
>             "msa": {
>                 "exp": 1111111111,
>                 "extra": {
>                     "ext_expires_in": 3600,
>                     "state": "ssssssss"
>                 },
>                 "iat": 1111111111,
>                 "refresh_token": "",
>                 "token": ""
>             },
>             "msa-client-id": "ssssssssssssssssssssssssssssssssssss",
>             "profile": {
>                 "cape": "ssssssssssssssssssssssssssssssssssss",
>                 "capes": [
>                     {
>                         "alias": "Vanilla",
>                         "id": "ssssssssssssssssssssssssssssssssssss",
>                         "url": "ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss"
>                     }
>                 ],
>                 "id": "ssssssssssssssssssssssssssssssss",
>                 "name": "nick",
>                 "skin": {
>                     "data": "",
>                     "id": "ssssssssssssssssssssssssssssssssssss",
>                     "url": "sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss",
>                     "variant": "CLASSIC"
>                 }
>             },
>             "type": "MSA",
>             "utoken": {
>                 "exp": 1111111111,
>                 "extra": {
>                     "uhs": "1111111111111111111"
>                 },
>                 "iat": 1111111111,
>                 "token": ""
>             },
>             "xrp-main": {
>                 "exp": 1111111111,
>                 "extra": {
>                     "agg": "sssss",
>                     "gtg": "sssssssssssss",
>                     "prv": "sss",
>                     "uhs": "1111111111111111111",
>                     "usr": "1111111",
>                     "utr": "111",
>                     "xid": "1111111111111111"
>                 },
>                 "iat": 1111111111,
>                 "token": ""
>             },
>             "xrp-mc": {
>                 "exp": 1111111111,
>                 "extra": {
>                     "uhs": "1111111111111111111"
>                 },
>                 "iat": 1111111111,
>                 "token": ""
>             },
>             "ygg": {
>                 "exp": 1111111111,
>                 "iat": 1111111111,
>                 "token": ""
>             }
>         }
>     ],
>     "formatVersion": 3
> }

I have same problem, did you find a fix? I am using latest version from PrismLauncher, started single player, and enabled lan. Can see server via "add server" but when connecting same error

**Comment by Edgaras91** [comment]
Seems like hosting on Windows 11 machine was giving this error, but not when hosting on Windows 10. Also this windows 10 hosting was auto-discovered in the multiplayer screen.
